### PR TITLE
DL-14: Update travis' configuration file.

### PR DESCRIPTION
**Pull request by franckcuny**
Add Apache's license headers, update the link to the correct build, and add instructions to build on OSX.

### CODE REVIEW

**Comment by franckcuny** [comment]
This is not working for OS X [1], I'll find a working solution

[1] https://travis-ci.org/apache/incubator-distributedlog/jobs/147085916

**Comment by franckcuny** [comment]
The new configuration builds for OSX [1] and Linux [2].

[1] https://travis-ci.org/apache/incubator-distributedlog/jobs/147087414
[2] https://travis-ci.org/apache/incubator-distributedlog/jobs/147087413

**Comment by sijie** [comment]
The change looks good to me. But I will first port the bookkeeper merge-pr script to distributedlog. Then merge the pr can automatically close the corresponding ticket.

**Comment by sijie** [comment]
I created a jira https://issues.apache.org/jira/browse/DL-16 to port the merge script.

**Comment by sijie** [comment]
Also I am thinking of cloning the process of BookKeeper about pull-requests and merge scripts. 

https://cwiki.apache.org/confluence/display/BOOKKEEPER/Contributing+to+BookKeeper
https://cwiki.apache.org/confluence/display/BOOKKEEPER/Patch+Sumission

So it would be making sense to change this pull request title to be "DL-14: Update travis' configuration file". so when we close this pr request, there will be comments updated on DL-14. (as we enabled the github integration hooks at INFRA-12245.

**Comment by sijie** [comment]
LGTM +1

**Pull request closed without merging**
