### PR TITLE
(WIP) Kafka publisher uses distributed log streams as partitions

### PR DESCRIPTION
**Pull request by khurrumnasimm**
- moved the distributedlog-kafka module out of tutorials module, so people can use it directly
- rewrote the kafka client example to use kafka config, key/value serializer, partitioner and such

### CODE REVIEW

**Comment by leighst** [comment]
my feeling is that this is supposed to be a simple tutorial and it should live in the tutorials section.

there is a question of layering here. dl should be concerned with serving individual streams. we have a separate project which may get open sourced at some point which sits above the DL layer and partitions streams. if we released that it would be totally separated.

@sijie may have a different opinion

**Comment by sijie** [comment]
@leighst @khurrumnasimm I commented in the email thread. I am kind of agreeing with Leigh about the focus on DistributedLog. however I also wouldn't discourage the work here. It might be good to keep the module under distributedlog-tutorials or move to 'distributedlog-contribs' to keep the project focused.

**Comment by sijie** [comment]
@khurrumnasimm Any updates about this?

**Comment by sijie** [comment]
mind closing this PR? if it is no active.

**Comment by khurrumnasimm** [comment]
@sijie currently I don't have enough time to work on this. closing this pull and will send out another one if I am done with that work.

**Pull request closed without merging**
