### PR TITLE
[blog] A technical review of kafka and distributedlog

### PR DESCRIPTION
**Pull request by sijie**

### CODE REVIEW

**Comment by sijie** [comment]
@leighst I will go ahead and merge this. any objections?

**Comment by sijie** [comment]
@leighst fixed the broken ledger url and the post date

**Comment by sijie** [comment]
@leighst I fixed the post date but left the permalink unchanged. http://distributedlog.incubator.apache.org/technical-review/2015/09/19/kafka-vs-distributedlog.html

**Comment by sijie** [comment]
@leighst FYI. I merged this pull request.

**Comment by leighst** [comment]
lgtm

**Pull request closed without merging**
