### PR TITLE
DL-32: Update findbugs version to 3.0.3

### PR DESCRIPTION
**Pull request by franckcuny**
The previous version (2.5.2) is not compatible with Java 8.

### CODE REVIEW

**Comment by franckcuny** [comment]
I'm unable to run successfully `mvn findbugs:findbugs` at the moment, I keep hitting this issue:

```
[ERROR] Failed to execute goal on project distributedlog-core: Could not resolve dependencies for project com.twitter:distributedlog-core:jar:0.3.51-SNAPSHOT: Could not find artifact com.twitter:distributedlog-protocol:jar:0.3.51-SNAPSHOT in bookkeeper-twitter-mvn-repo (https://raw.github.com/twitter/bookkeeper/mvn-repo/4.3.5-TWTTR-OSS) -> [Help 1]
```

It looks like the name on GitHub is RELEASE4.3.5-TWTTR-OSS

**Comment by sijie** [comment]
@franckcuny I think you might need to run `mvn clean install -DskipTests` first and then run `mvn findbugs:findbugs`. `Findbugs` runs when the code is compiled.

**Comment by sijie** [comment]
Also, I think we also need to make code changes to address findbugs errors if there are any.

**Comment by franckcuny** [comment]
got it, giving it a try.

**Comment by franckcuny** [comment]
```
[INFO] Apache DistributedLog :: Parent .................... SUCCESS [  1.204 s]
[INFO] Apache DistributedLog :: Protocol .................. SUCCESS [ 12.080 s]
[INFO] Apache DistributedLog :: Core Library .............. SUCCESS [ 21.945 s]
[INFO] Apache DistributedLog :: Proxy Client .............. SUCCESS [  8.245 s]
[INFO] Apache DistributedLog :: Proxy Service ............. SUCCESS [ 10.518 s]
[INFO] Apache DistributedLog :: Benchmark ................. SUCCESS [  8.050 s]
[INFO] Apache DistributedLog :: Example ................... SUCCESS [  3.790 s]
[INFO] Apache DistributedLog :: Tutorials :: Basics ....... SUCCESS [  4.764 s]
[INFO] Apache DistributedLog :: Tutorials :: Messaging Tutorial SUCCESS [  5.131 s]
[INFO] Apache DistributedLog :: Tutorials :: Kafka Tutorial SUCCESS [  4.903 s]
[INFO] Apache DistributedLog :: Tutorials :: MapReduce Tutorial SUCCESS [  6.082 s]
[INFO] Apache DistributedLog :: Tutorials ................. SUCCESS [  0.003 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:27 min
[INFO] Finished at: 2016-09-10T13:05:45-07:00
[INFO] Final Memory: 36M/399M
[INFO] ------------------------------------------------------------------------
```

**Comment by franckcuny** [comment]
Running `mvn findbugs:check` reports error, I'm going to update the PR.

**Comment by sijie** [comment]
just realized that @jderrickk was doing the same same at #19

**Comment by sijie** [comment]
@franckcuny I think findbugs was added in #19 . mind closing this PR?

**Pull request closed without merging**
