### PR TITLE
DL-204: Bump libthrift to latest version for distributedlog-core

### PR DESCRIPTION
**Pull request by sijie**
Currently finagle heavily depends on an out-of-dated version - libthrift 5.0. Proxy modules (client, server) depend on this version, however the core library doesn't really depend on libthrift. 

This change is to change libthrift to 0.9.* in distributedlog-core and shade it to avoid it conflict with the version used by finagle.

This change is based on #131 . The main change is at gitsha [6e58786](https://github.com/apache/incubator-distributedlog/commit/6e587869f87cdce50ae93ba3d52767719d1ab5a6)

### CODE REVIEW

**Comment by leighst** [comment]
Is this version back compatible with the finagle version?
Do we still use old thrift in proxy-server? Etc.?
Whats the long term plan here? Should we get rid of hard dependency on finagle and modularize the serving component?

**Comment by sijie** [comment]
@leighst : it is format backward compatible, but not binary compatible. I only change the library in distributedlog-core and shade it. The other modules - proxy-protocol, proxy-client and proxy-server that depend on finagle, will still use the libthrift 0.5.

I think the log term plan:

- for proxy-server, it should be able to support multiple protocol bindings: finagle, gRPC, maybe even kafka protocol.
- for client, we might just build different client: finagle one talking to thrift endpoint, gRPC one talking to gRPC endpoint.

**Comment by leighst** [comment]
@sijie the usage of thrift in core is pretty limited, seems like
* BKDLConfig etc
* ZKAccessControl etc

Whats the motivation for this change? Just trying to avoid pulling in an old thrift lib when core is used?

**Comment by sijie** [comment]
@leighst a couple of reasons:

- trying to reduce the number of dependencies in distributedlog-core
- the libthrift-5 library only exist in twitter.maven.com. I am in favor of moving to a library that lives in maven central. it is updated with thrift project. no need to make distributedlog-core depend on twitter.maven.com.

**Comment by leighst** [comment]
@sijie dl-service will still depend on twitter maven though right?

**Comment by sijie** [comment]
yes dl-service, dl-client will still depend on twitter maven. because finagle-thrift depends on libthrift-5, which only exists at twitter maven.

**Pull request closed without merging**
