### PR TITLE
DL-3: Move distributedlog website to apache (part 1)

### PR DESCRIPTION
**Pull request by sijie**
Setup an initial distributedlog website using jekyll & bootstrap.

Live demo: https://sijie.github.io/incubator-distributedlog/

### CODE REVIEW

**Comment by leighst** [comment]
+1

**Comment by leighst** [comment]
On second thought criss crossing from one site to another like this is awkward. 

Why cant we just use sphinx?

Its also a lot of irritating web code to have to maintain.

**Comment by franckcuny** [comment]
@sijie is this still relevant ? Based on your email this week regarding the tests you've done with some plugin to convert the doc.

**Comment by sijie** [comment]
@franckcuny this is the pull request to use jekyll-rst plugin to compile those rst files to static html content.

**Comment by leighst** [comment]
+1, shipit

**Pull request closed without merging**
