### PR TITLE
add global cluster deploy instructions

### PR DESCRIPTION
**Pull request by leighst**
Add global cluster setup instructions

### CODE REVIEW

**Comment by Johnlon** [comment]
How feasible would it be to configure this as an Ansible playbook - executable documentation and all that?

**Comment by franckcuny** [comment]
It would not be too difficult. However, I don't think this should be in this repo if we create such things. We could create a new repository regarding ansible. (If we think it's worthwhile I don't mind starting that, I've some experience with both DLog and ansible :)

**Comment by sijie** [comment]
+1 for the idea. @franckcuny I don't have an experience with ansible. so I will just defer this to you :D

**Comment by khurrumnasimm** [comment]
+1 for the Ansible playbook. when do you guys think it can be available?

**Pull request closed without merging**
