### PR TITLE
DL-192: year needs updating in NOTICE

### PR DESCRIPTION
**Pull request by sijie**
The year was 2016. but we are going to release at 2017. so updating the files to 2017.

### CODE REVIEW

**Comment by leighst** [comment]
does this need to be a template eventually?

ie does every new release need to use the current year?

**Comment by sijie** [comment]
I think this has to be updated on every new release to use current year. I will check if there is any plugin can be used for automating this.

**Comment by fpj** [comment]
If you find a way to automate, then great, but otherwise, just add a bullet to the release management page to remind the release manager to update if necessary.

**Comment by sijie** [comment]
@fpj yeah. will first add a bullet to release guide for now.

**Pull request closed without merging**
