### PR TITLE
DL-4: Add NOTICE file.

### PR DESCRIPTION
**Pull request by franckcuny**

### CODE REVIEW

**Comment by fpj** [comment]
@franckcuny you may have seen this already, but just in case you may want to have a look at the instructions here:

http://www.apache.org/dev/licensing-howto.html

**Comment by sijie** [comment]
The notice file looks good to me. +1.

@fpj did you see any problem here?

**Comment by fpj** [comment]
@franckcuny @sijie It looks good, but I haven't done an inspection of dependencies and such to determine whether we have anything we need to add to the notice file. That's main reason why I shared the link above.

**Comment by sijie** [comment]
LGTM +1

**Pull request closed without merging**
