### PR TITLE
Hack week cleanup

### PR DESCRIPTION
**Pull request by franckcuny**
This is still in progress.

- remove trailing white spaces in a few places
- fix some scripts (not rely on git); style consistency
- validate that the vagrant configuration works
- one of the Dockerfile was not correct

### CODE REVIEW

**Comment by franckcuny** [comment]
This is actually still broken.

**Comment by sijie** [comment]
@franckcuny the travis ci passed. looking into apache ci now.

**Comment by franckcuny** [comment]
Here are a few test:

``` shell
asf-distributedlog % cd distributedlog-service/
distributedlog-service % ./bin/dlog admin
JMX enabled by default
DLOG_HOME => ./bin/..
Usage: dlog_admin <command>

        bind               : bind the bookkeeper environment settings for a given distributedlog instance.
        delete_stream_acl  : Delete ACL for a given stream
        dlck               : Check and repair a distributedlog namespace
        help               : describe the usage of this tool or its sub-commands.
        repairseqno        : Repair a stream whose inprogress log segment has lower sequence number.
        set_default_acl    : Set Default ACL for a namespace
        set_stream_acl     : Set Default ACL for a given stream
        unbind             : unbind the bookkeeper environment bound for a given distributedlog instance.

```

``` shell
distributedlog-service % ls -l ../dist/
distributedlog-service % ./bin/bundle >/dev/null
distributedlog-service % ls -l ../dist/
total 99376
drwxr-xr-x  5 fcuny  staff       170 Dec 15 16:07 distributedlog-service
-rw-r--r--  1 fcuny  staff  50878174 Dec 15 16:07 distributedlog-service.zip
distributedlog-service % cd ../distributedlog-benchmark/
distributedlog-benchmark % ./bin/bundle > /dev/null
distributedlog-benchmark % ls -l ../dist/
total 199952
drwxr-xr-x  5 fcuny  staff       170 Dec 15 16:08 distributedlog-benchmark
-rw-r--r--  1 fcuny  staff  51492479 Dec 15 16:08 distributedlog-benchmark.zip
drwxr-xr-x  5 fcuny  staff       170 Dec 15 16:07 distributedlog-service
-rw-r--r--  1 fcuny  staff  50878174 Dec 15 16:07 distributedlog-service.zip
```

@sijie I'd rather squash some of the commits instead of having 10+ commits merged (unless you prefer it that way).

If I have a shipit, I'll squash and push again to this branch.

**Comment by franckcuny** [comment]
Going to try again to build the vagrant images too.

**Comment by sijie** [comment]
@franckcuny +1 

the merge script will squash the commits. so you don't need to manually squash

**Pull request closed without merging**
