### PR TITLE
DL-25: Documentation for vagrant and docker deployment

### PR DESCRIPTION
**Pull request by arvindkandhare**

### CODE REVIEW

**Comment by sijie** [comment]
This looks good to me! +1

But can you create a jira under https://issues.apache.org/jira/browse/DL and changed the pull request title to be "DL-XXX: ...".

So the pull request will be connected with a jira ticket.

**Comment by arvindkandhare** [comment]
Done. Somehow not able to assign the issue to myself. Everything else is taken care of :)

**Comment by sijie** [comment]
@arvindkandhare I just added you to contributor list and assigned that ticket to you. so we are good now. 

we are working on porting the merge-pr.py script from bookkeeper ( @franckcuny is helping on that ). Once we have the script in, we will start merging these pull requests.

**Comment by sijie** [comment]
@franckcuny can you review this also? I'd like to have a second eye on documentation.

**Comment by franckcuny** [comment]
LGTM. It's a good starting point, we can improve from here.

**Pull request closed without merging**
