### PR TITLE
DL-193: Bumped up the Guava version

### PR DESCRIPTION
**Pull request by arvindkandhare**
Moving the Guava version from 16.0 to 20.0.

### CODE REVIEW

**Comment by hsaputra** [comment]
LGTM
+1

**Comment by hsaputra** [comment]
Couldnt figure out why our Jenkins build failed

**Comment by arvindkandhare** [comment]
Looking in to this. mvn compile passed for me locally. Maybe I should try running mvn clean install? Giving it a shot.

**Comment by sijie** [comment]
Seems both travis CI and Jenkins failed with similar error

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project distributedlog-service_2.11: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/travis/build/apache/incubator-distributedlog/distributedlog-service && /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java -Xmx3G -Djava.net.preferIPv4Stack=true -XX:MaxDirectMemorySize=2G -jar /Users/travis/build/apache/incubator-distributedlog/distributedlog-service/target/surefire/surefirebooter1574788574072023345.jar /Users/travis/build/apache/incubator-distributedlog/distributedlog-service/target/surefire/surefire1040382260065287155tmp /Users/travis/build/apache/incubator-distributedlog/distributedlog-service/target/surefire/surefire_871857929376723744956tmp
`

**Comment by arvindkandhare** [comment]
While the compile passes, the tests actually try to create a server process. This tries to start bookkeeper server, which has dependencies on Guava again. This means that this PR needs changes to the Bookkeeper pulled from: https://github.com/twitter/bookkeeper/. 
As Guava has moved and changed the API quiet a bit, this is an involved changed. Another interesting point is that Apache bookkeeper uses even older version of Guava (13.0 in their master branch). So this PR should not go in before the Twitter bookkeeper moves towards this version.

Do share your views on this.

**Comment by jiazhai** [comment]
Thanks for the fix.

**Comment by sijie** [comment]
@arvindkandhare can you just exclude "guava" from the bookkeeper dependency and use 0.20 here? I am trying to understand if we really need a new bk version from twitter branch.

**Comment by sijie** [comment]
gotcha. Is it possible to shade the guava in bookkeeper?

**Comment by sijie** [comment]
@arvindkandhare - I merged your change in bookkeeper and released a version - 4.3.7-TWTTR-OSS 

Can you update your pull request for this?

**Comment by sijie** [comment]
LGTM +1. Thanks @arvindkandhare

**Pull request closed without merging**
