### PR TITLE
DL-16: Add script to merge GitHub PR.

### PR DESCRIPTION
**Pull request by franckcuny**
Fetch a list of open Pull Request from GitHub, and merge them into the
repository. If the JIRA credentials are exported, the issues related to
the PR are updated with a comment and closed.

This script is a modified version of the one created for the spark
project.

```
./dl-merge-pr.py
Which pull request would you like to merge? (e.g. 34): 2
Commit title [DL-4: Add NOTICE file.]:

=== Pull Request #2 ===
PR title	DL-4: Add NOTICE file.
Commit title	DL-4: Add NOTICE file.
Source		franckcuny/fcuny/DL-4
Target		master
URL		https://api.github.com/repos/apache/incubator-distributedlog/pulls/2

Proceed with merging pull request #2? (y/n): y
From https://github.com/apache/incubator-distributedlog
 * [new ref]         refs/pull/2/head -> PR_TOOL_MERGE_PR_2
From git://git.apache.org/incubator-distributedlog
 * [new branch]      master     -> PR_TOOL_MERGE_PR_2_MASTER
Switched to branch 'PR_TOOL_MERGE_PR_2_MASTER'
Do you want to validate unit tests after the merge? (y/n): n
Enter primary author in the format of 'name <email>' [Franck Cuny <fcuny@apache.org>]:
Enter reviewers [Sijie Guo <sijie@apache.org>]:

Merge complete (local ref PR_TOOL_MERGE_PR_2_MASTER). Push to apache? (y/n): n
Okay, exiting
Restoring head pointer to fcuny/DL-16
Switched to branch 'fcuny/DL-16'
```

### CODE REVIEW

**Comment by yzang** [comment]
Creating a JIRA ticket https://issues.apache.org/jira/browse/DL-26 for tracking Travis CI build failure.

**Comment by sijie** [comment]
LGTM +1. Let's merge this pull request using it :D 

Also, I created a wiki page for 'committer workflow' - do you mind filling up the information on how to use this script for committers?

https://cwiki.apache.org/confluence/display/DL/Committer+Workflow

**Comment by franckcuny** [comment]
I'll update the wiki.

**Comment by sijie** [comment]
@franckcuny I merged this pull request. but because the commit message doesn't contain 'close #6' message. so asfgit doesn't close this pull request. Can you manually close this pull request?

The fix for the merge script is on https://github.com/apache/incubator-distributedlog/pull/6. If it is okay to you, can you try to merge that? it would help testing if you have permissions to push the change to apache.

**Comment by franckcuny** [comment]
This change has been merged.

**Pull request closed without merging**
