### PR TITLE
DL-140 : Fix distributedlog-core findbug inconsistent synchronization warings

### PR DESCRIPTION
**Pull request by xieliang**

### CODE REVIEW

**Comment by franckcuny** [comment]
@xieliang could you verify if the failure is due to your change ? Is the test passing on your local environment ?

cc @sijie

**Comment by sijie** [comment]
@franckcuny I passed the travis ci for both scala 2.10 and 2.11. it should be transient errors.

**Comment by sijie** [comment]
@xieliang the change looks good. but I am interested to see how did you find this. I thought we already enable findbugs on ci jobs. I am wondering why didn't we detect the findbug warnings.

**Comment by xieliang** [comment]
I ran the findbug (3.0.1) binary on my local devbox. Those multi-thread warings exist even after importing the findbug exclude xml file manually,  what's the findbugs binary version at ci side, i guess it's obsolete...

**Comment by sijie** [comment]
@xieliang I think currently we are using 3.0.3 in the pom.xml file.

`      
    <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>findbugs-maven-plugin</artifactId>
        <version>3.0.3</version>
      </plugin>
`
The travis ci runs "findbugs:check" for every pull request - "mvn --batch-mode clean package findbugs:check"

is it the same command that you are running?

**Comment by xieliang** [comment]
It's not the same thing. The travis ci runs with "findbugs-maven-plugin", and i ran with findbugs binary package. 
(From http://gleclaire.github.io/findbugs-maven-plugin/index.html , i see the core findbugs version are all 3.0.1.)
Let me finger out the diff later

**Comment by xieliang** [comment]
@sijie , in distributedlog-core pom.xml, if you add "<threshold>Low</threshold>" after "<excludeFilterFile>"  config item, you will see sth like this:
[INFO] BugInstance size is 120
[INFO] Error size is 0
[INFO] Total bugs: 120

Just like my result from findbugs gui view.

**Comment by sijie** [comment]
@xieliang gotcha. it might be worth having a jira to make the findbugs threshold 'LOW'. and in this jira, we need to fix those findbug warnings.

for this pr, I think it is good to fix synchronization issue.

**Comment by sijie** [comment]
@xieliang do you mind rebasing this pr to latest master? so it would trigger the checks again.

**Comment by xieliang** [comment]
Rebased.  
"it might be worth having a jira to make the findbugs threshold 'LOW'. and in this jira, we need to fix those findbug warnings."  , i'll create a new jira.

**Pull request closed without merging**
