### PR TITLE
DL-4: Repackage the source under apache namespace

### PR DESCRIPTION
**Pull request by khurrumnasimm**
Repackage the source code from 'com.twitter.distributedlog' to 'org.apache.distributedlog'.

It is a huge change, but I basically just renamed the files and changed the package name. Let me know if it is okay.

### CODE REVIEW

**Comment by sijie** [comment]
@khurrumnasimm thank you so much for your effort. This is not a trivial change. I think most of changes are just renaming files and package names. so +1 from me. 

but I'd like to see what other people's opinion. @leighst ?

**Comment by khurrumnasimm** [comment]
ping again @leighst @sijie

**Comment by sijie** [comment]
@khurrumnasimm sorry for being late. the change LGTM. +1

**Comment by leighst** [comment]
+1

**Comment by sijie** [comment]
@leighst @khurrumnasimm I would like to put this as last change to merge for the first apache release. since we might have quite a few changes to merge based on current package name.

@khurrumnasimm do you have any script for repacking this?

**Comment by sijie** [comment]
@khurrumnasimm we almost finished merging changes back to the master branch. I would like to proceed with this pull request next week and cut the first release candidate. if you have the script for repackaging the whole project, can you share the script?

**Comment by khurrumnasimm** [comment]
@sijie I added a script "scripts/dev/repackage.sh". it is included in this pull request.

I think the easiest way to coordinate with this pull request - when you guys merge this pull request, you can run the script to repackage the files. what do you think?

**Comment by khurrumnasimm** [comment]
@leighst @sijie I will close this pull request, as I sent a separate pull request #95 for the script.

**Pull request closed without merging**
